In [1]:
[[12,34,56,45,34],[],[]]

[[12, 34, 56, 45, 34], [], []]

In [36]:
import numpy
n=numpy.arange(24)

In [37]:
no=numpy.arange(24)

In [38]:
no

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [40]:
type(n)
n.reshape(2,2,6)

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])

In [54]:
import cv2
imp=cv2.imread("smallgray.png",1)

In [60]:
ims=numpy.hstack((n,n))
ims

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
       10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])